var challenge = {
	title: 'Nearest Lucky Numbers',
	description: 'A Lucky Number is a natural number in a set which is generated by a certain "sieve". This sieve is similar to the Sieve of Eratosthenes that generates the primes, but it eliminates numbers based on their position in the remaining set, instead of their value (or position in the initial set of natural numbers).',
	difficulty: 'easy',
	reddit: 'https://www.reddit.com/r/dailyprogrammer/comments/6wjscp/2017828_challenge_329_easy_nearest_lucky_numbers/',
	inputs: [{type: 'text', name: 'c1_number', title: 'Your number'}],
	outputs: [{ type: 'text', name: 'c1_output', title: 'Result' }, { type: 'text', name: 'c1_time', title: 'Time' }],
	run: function () {
		var startTimer = new Date();

		var inputNumber = $('#' + this.inputs[0].name).val();
		var answer = '';

		var numbers = new Array(0, inputNumber);
		for (var i = 0; i <= inputNumber; i++) {
			numbers[i] = i * 2 - 1;
		}

		var luckyIndex = 3;
		var nextLower = 0;
		var luckyNumbers = [];
		var numbersChecked = 0;

		while (true) {
			answer = CheckNumbers();
			if (answer != '')
				break;

			for (var j = 0; j < numbers.length; j++) {
				if (j % luckyIndex == 0) {
					numbers.splice(j, 1);
				}
			}

			luckyNumbers = numbers.slice(0, luckyIndex - 1);
			luckyIndex++;
		}

		var endTimer = new Date();
		$('#' + this.outputs[0].name).val(answer);
		$('#' + this.outputs[1].name).val(FormatMS(endTimer - startTimer));

		function CheckNumbers() {
			for (var y = numbersChecked; y < luckyNumbers.length; y++) {
				if (luckyNumbers[y] > nextLower && luckyNumbers[y] < inputNumber) {
					nextLower = luckyNumbers[y];
				} else if (luckyNumbers[y] > inputNumber) {
					return 'Next lower: ' + nextLower + ' - Next higher: ' + luckyNumbers[y] + '!';
					break;
				} else if (luckyNumbers[y] == inputNumber) {
					return inputNumber + ' is a lucky number!';
					break;
				}
			}

			return '';
		}
	}
}





var $input_number;
var $output_text;
var $output_time;

function Init() {
	// Prepare
	ClearContent();
	InitInputs();
	InitOutputs()

	// Navigation
	SetNavigationTitle('Nearest Lucky Numbers');
	SetNavigationDescription('This is a test');

	// Display
	DisplayChallenge();
}

function InitInputs() {
	$input_number = CreateTextInput('Number', 'input_number');
}

function InitOutputs() {
	CreateRunButton('Run Challenge');
	$output_text = CreateTextOutput('Result', 'result');
	$output_time = CreateTextOutput('Time', 'time');
}

function Run() {

	
}